#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xvfb-run
Version  : 1.20.0
Release  : 3
URL      : http://localhost/cgit/projects/xvfb-run/snapshot/xvfb-run-1.20.0.tar.gz
Source0  : http://localhost/cgit/projects/xvfb-run/snapshot/xvfb-run-1.20.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: xvfb-run-bin
Requires: xvfb-run-man
Requires: xorg-server-bin

%description
No detailed description available

%package bin
Summary: bin components for the xvfb-run package.
Group: Binaries
Requires: xvfb-run-man

%description bin
bin components for the xvfb-run package.


%package doc
Summary: doc components for the xvfb-run package.
Group: Documentation
Requires: xvfb-run-man

%description doc
doc components for the xvfb-run package.


%package man
Summary: man components for the xvfb-run package.
Group: Default

%description man
man components for the xvfb-run package.


%prep
%setup -q -n xvfb-run-1.20.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534354874
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1534354874
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/xvfb-run
cp copyright %{buildroot}/usr/share/doc/xvfb-run/copyright
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xvfb-run

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/xvfb\-run/*

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/xvfb-run.1
