#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xvfb-run
Version  : 1.20.0
Release  : 6
URL      : http://localhost/cgit/projects/xvfb-run/snapshot/xvfb-run-1.20.0.tar.gz
Source0  : http://localhost/cgit/projects/xvfb-run/snapshot/xvfb-run-1.20.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: xvfb-run-bin = %{version}-%{release}
Requires: xvfb-run-license = %{version}-%{release}
Requires: xvfb-run-man = %{version}-%{release}
Requires: which
Requires: xauth
Requires: xorg-server-bin
BuildRequires : which
BuildRequires : xauth
Patch1: 0001-Replace-tempfile-with-mktemp-command.patch

%description
No detailed description available

%package bin
Summary: bin components for the xvfb-run package.
Group: Binaries
Requires: xvfb-run-license = %{version}-%{release}

%description bin
bin components for the xvfb-run package.


%package license
Summary: license components for the xvfb-run package.
Group: Default

%description license
license components for the xvfb-run package.


%package man
Summary: man components for the xvfb-run package.
Group: Default

%description man
man components for the xvfb-run package.


%prep
%setup -q -n xvfb-run-1.20.0
cd %{_builddir}/xvfb-run-1.20.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1602193214
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1602193214
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xvfb-run
cp %{_builddir}/xvfb-run-1.20.0/copyright %{buildroot}/usr/share/package-licenses/xvfb-run/11d1ae389a1a78f7832586e4c2a0c3c7263b7475
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xvfb-run

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xvfb-run/11d1ae389a1a78f7832586e4c2a0c3c7263b7475

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xvfb-run.1
